import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });
// const poppins = Poppins({ subsets: ["latin"],
//   weights: [`100`, `200`, `300`, `400`, `500`, `600`, `700`, `800`, `900`],
//  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${inter.className} w-[80%] mx-auto px-4 text-black bg-white dark:bg-black dark:text-white`}>
        <Navbar />
        <main className="min-h-[calc(100vh-160px)] p-4 ">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
